#!/usr/bin/python

BASE_OID = '.1.3.6.1.4.1.25359.3'

import sys, commands, re, snmpresponse

def netsnmp():
    output = commands.getoutput("kstat -p ipnet:0:ipnet_stats:acceptFail")
    try:
        return re.split("\s+", output)
    except:
        return 0

def ipnet_stats_af(oid):
    return ('counter', int(netsnmp()[1]))

result = [
    ( BASE_OID + '.2.1.0', ipnet_stats_af),
]

operation = sys.argv[1]
req_oid = sys.argv[2]

snmpresponse.respond_to(operation, req_oid, result)

