#!/usr/bin/python

BASE_OID = '.1.3.6.1.4.1.25359.2'

import sys, commands, re, snmpresponse

def nfsutil():
    output = commands.getoutput("./nfsutil.d")
    try:
        return re.split("\s+", output)
    except:
        return 0

def max_nfs_req(oid):
    return ('gauge', int(nfsutil()[0]))

def max_active_threads(oid):
    return ('gauge', int(nfsutil()[1]))

def thread_pool_util(oid):
    return ('gauge', int(nfsutil()[2]))

result = [
    ( BASE_OID + '.2.1.0', max_nfs_req),
    ( BASE_OID + '.2.2.0', max_active_threads),
    ( BASE_OID + '.2.3.0', thread_pool_util),
]

operation = sys.argv[1]
req_oid = sys.argv[2]

snmpresponse.respond_to(operation, req_oid, result)

