#!/usr/bin/python

import sys

import simplejson as json

import snmpresponse
from tools.configuration import ZPOOLS_CACHE_FILE, ZPOOLS_IO_CACHE_FILE
from tools.configuration import ZPOOLS_IO_BASE_OID as BASE_OID


def zpio_calloc(pool):
    return 'gauge', zpios[pool][pool]['calloc']  # MB


def zpio_cfree(pool):
    return 'gauge', zpios[pool][pool]['cfree']  # MB


def zpio_oread(pool):
    return 'gauge', zpios[pool][pool]['oread']  # I/O operations


def zpio_owrite(pool):
    return 'gauge', zpios[pool][pool]['owrite'] # I/O operations


def zpio_bread(pool):
    return 'gauge', zpios[pool][pool]['bread']  # units/sec


def zpio_bwrite(pool):
    return 'gauge', zpios[pool][pool]['bwrite']  # units/sec


def zpio_lread(pool):
    return 'gauge', zpios[pool][pool]['lread']  # msecs


def zpio_lwrite(pool):
    return 'gauge', zpios[pool][pool]['lwrite']  # msecs


# nymnetworks     OBJECT IDENTIFIER ::= {enterprises 25359}
# zpooliostat     OBJECT IDENTIFIER ::= {nymnetworks 1}
# zpio            OBJECT IDENTIFIER ::= {zfs 1}

zpools = json.load(open(ZPOOLS_CACHE_FILE))
zpios = json.load(open(ZPOOLS_IO_CACHE_FILE))

result = []

i = 1
for pool in zpools:
    result.append((BASE_OID + '.2.1.' + str(i), ('string', pool)))
    result.append((BASE_OID + '.2.2.' + str(i), lambda oid, fs=pool: zpio_calloc(fs)))
    result.append((BASE_OID + '.2.3.' + str(i), lambda oid, fs=pool: zpio_cfree(fs)))
    result.append((BASE_OID + '.2.4.' + str(i), lambda oid, fs=pool: zpio_oread(fs)))
    result.append((BASE_OID + '.2.5.' + str(i), lambda oid, fs=pool: zpio_owrite(fs)))
    result.append((BASE_OID + '.2.6.' + str(i), lambda oid, fs=pool: zpio_bread(fs)))
    result.append((BASE_OID + '.2.7.' + str(i), lambda oid, fs=pool: zpio_bwrite(fs)))
    result.append((BASE_OID + '.2.8.' + str(i), lambda oid, fs=pool: zpio_lread(fs)))
    result.append((BASE_OID + '.2.9.' + str(i), lambda oid, fs=pool: zpio_lwrite(fs)))
    i += 1

operation = sys.argv[1]
req_oid = sys.argv[2]

snmpresponse.respond_to(operation, req_oid, result)
